import { useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router'
import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, Database, Download, ExternalLink, FileText, FolderKanban, Lightbulb, Plus, Search } from 'lucide-react'
import { dataKindLabel, knowledgeCategoryLabel, learningKindLabel, learningStatusLabel, reviewStatusLabel } from './domain'
import { DataAssetForm, KnowledgeForm, LearningForm } from './formsKnowledge'
import { useDemo } from './store'
import { Card, Empty, Modal, Notice, PageHeading, TaskRow, useToast } from './ui'
import { dateLabel, normalise, relativeLabel, todayISO } from './utils'

const Back = ({ to, label }: { to: string; label: string }) => <Link className="back-link" to={to}><ArrowLeft size={16} />{label}</Link>
const Missing = ({ name, to }: { name: string; to: string }) => <div className="not-found"><h1>Không tìm thấy {name}</h1><Link className="button primary" to={to}>Quay lại danh sách</Link></div>
const safeSource = (url?: string) => url && (/^https?:\/\//i.test(url) || url.startsWith('/demo/')) ? url : undefined
const Meta = ({ children }: { children: React.ReactNode }) => <span className="hub-meta-item">{children}</span>

export function LearningPage() {
  const { state } = useDemo(); const navigate = useNavigate(); const [modal, setModal] = useState(false)
  const [query, setQuery] = useState(''); const [kind, setKind] = useState('all'); const [status, setStatus] = useState('all')
  const items = state.learning.filter(item => !item.archived).filter(item => (kind === 'all' || item.kind === kind) && (status === 'all' || item.status === status) && (!query || normalise(`${item.title} ${item.objective} ${item.notes} ${item.nextAction}`).includes(normalise(query))))
  const open = state.learning.filter(item => !item.archived && item.status === 'active')
  const review = open.filter(item => item.nextReviewAt && item.nextReviewAt <= todayISO())
  return <>
    <PageHeading eyebrow="NĂNG LỰC ĐANG XÂY" title="Học & nghiên cứu" description="Theo dõi nội dung đang học, câu hỏi đang nghiên cứu, nguồn và bước tiếp theo." action={<button className="button primary" onClick={() => setModal(true)}><Plus size={17} /> Thêm nội dung</button>} />
    <div className="hub-stats"><Card><span className="hub-stat-icon blue"><BookOpen size={19}/></span><strong>{open.length}</strong><small>Đang thực hiện</small></Card><Card><span className="hub-stat-icon orange"><Lightbulb size={19}/></span><strong>{state.learning.filter(item => !item.archived && item.kind === 'research').length}</strong><small>Đề tài nghiên cứu</small></Card><Card><span className="hub-stat-icon navy"><CalendarDays size={19}/></span><strong>{review.length}</strong><small>Đến ngày xem lại</small></Card></div>
    <div className="hub-filters"><div className="filter-search"><Search size={17}/><input aria-label="Tìm nội dung học nghiên cứu" placeholder="Tìm nội dung, mục tiêu, ghi chú..." value={query} onChange={e => setQuery(e.target.value)}/></div><select aria-label="Lọc loại nội dung" value={kind} onChange={e => setKind(e.target.value)}><option value="all">Mọi loại</option>{Object.entries(learningKindLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select aria-label="Lọc trạng thái học" value={status} onChange={e => setStatus(e.target.value)}><option value="all">Mọi trạng thái</option>{Object.entries(learningStatusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>
    <div className="hub-count">{items.length} nội dung trong bộ lọc</div>
    <div className="hub-grid">{items.map(item => { const project = state.projects.find(p => p.id === item.projectId); const related = state.knowledge.filter(k => !k.archived && k.learningId === item.id).length; return <Link className="hub-card" to={`/learning/${item.id}`} key={item.id}><div className="hub-card-top"><span className="hub-type">{learningKindLabel[item.kind]}</span><span className={`hub-status ${item.status}`}>{learningStatusLabel[item.status]}</span></div><h2>{item.title}</h2><p>{item.objective}</p><div className="hub-progress"><div style={{ width: `${item.progress}%` }}/></div><div className="hub-progress-label"><span>Tiến độ</span><strong>{item.progress}%</strong></div><div className="hub-next"><small>BƯỚC TIẾP THEO</small><span>{item.nextAction || 'Chưa đặt bước tiếp theo'}</span></div><div className="hub-card-foot"><span>{project?.title || 'Học tập chung'} · {related} bài học</span><span>{relativeLabel(item.nextReviewAt)} <ArrowRight size={16}/></span></div></Link> })}</div>
    {!items.length && <Card><Empty title="Chưa có nội dung phù hợp" description="Thử bộ lọc khác hoặc thêm nội dung đang học/nghiên cứu." /></Card>}
    {modal && <Modal title="Thêm nội dung học/nghiên cứu" onClose={() => setModal(false)} wide><LearningForm onClose={() => setModal(false)} onSaved={id => navigate(`/learning/${id}`)} /></Modal>}
  </>
}

export function LearningDetailPage() {
  const { id } = useParams(); const { state, update, archive } = useDemo(); const toast = useToast(); const navigate = useNavigate(); const [editing, setEditing] = useState(false); const [newKnowledge, setNewKnowledge] = useState(false)
  const item = state.learning.find(entry => entry.id === id && !entry.archived); if (!item) return <Missing name="nội dung học/nghiên cứu" to="/learning" />
  const project = state.projects.find(p => p.id === item.projectId); const related = state.knowledge.filter(k => !k.archived && k.learningId === item.id)
  return <><Back to="/learning" label="Học & nghiên cứu" /><PageHeading eyebrow={`${learningKindLabel[item.kind]} · ${learningStatusLabel[item.status]}`} title={item.title} description={item.objective} action={<div className="button-group"><button className="button outline" onClick={() => setEditing(true)}>Chỉnh sửa</button><button className="button primary" onClick={() => { update('learning', item.id, { status: item.status === 'done' ? 'active' : 'done', progress: item.status === 'done' ? item.progress : 100 }); toast('Đã cập nhật tiến độ trong dữ liệu demo.') }}>{item.status === 'done' ? 'Mở lại' : 'Đánh dấu hoàn tất'}</button></div>} />
    <div className="detail-grid"><div className="stack"><Card title="Ghi chép & điều rút ra"><p className="hub-prose">{item.notes || 'Chưa có ghi chép. Hãy thêm các điểm đã học và câu hỏi còn mở khi chỉnh sửa.'}</p><div className="inline-actions"><button className="button small outline" onClick={() => setNewKnowledge(true)}><Plus size={15}/> Lưu thành kiến thức</button></div></Card><Card title="Kiến thức liên quan">{related.length ? <div className="hub-link-list">{related.map(k => <Link key={k.id} to={`/knowledge/${k.id}`}><Lightbulb size={17}/><span><strong>{k.title}</strong><small>{knowledgeCategoryLabel[k.category]} · {reviewStatusLabel[k.reviewStatus]}</small></span><ArrowRight size={16}/></Link>)}</div> : <Empty title="Chưa có bài học liên kết" description="Chọn Lưu thành kiến thức để giữ lại điều hữu ích." />}</Card></div>
    <div className="stack"><Card title="Theo dõi tiến độ"><div className="hub-big-progress"><strong>{item.progress}%</strong><div className="hub-progress"><div style={{ width: `${item.progress}%` }}/></div></div><div className="detail-fields"><div><span>Trạng thái</span><strong>{learningStatusLabel[item.status]}</strong></div><div><span>Ngày xem lại</span><strong>{dateLabel(item.nextReviewAt)}</strong></div></div><div className="hub-next detail"><small>BƯỚC TIẾP THEO</small><span>{item.nextAction || 'Chưa đặt bước tiếp theo'}</span></div></Card><Card title="Nguồn & bối cảnh"><div className="hub-link-list">{project && <Link to={`/projects/${project.id}`}><FolderKanban size={17}/><span><strong>{project.title}</strong><small>Dự án liên quan</small></span><ArrowRight size={16}/></Link>}{safeSource(item.sourceUrl) && <a href={safeSource(item.sourceUrl)} target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/><span><strong>Mở nguồn học/nghiên cứu</strong><small>{item.sourceUrl}</small></span><ArrowRight size={16}/></a>}{!project && !item.sourceUrl && <Empty title="Chưa có liên kết nguồn" />}</div></Card><button className="text-button danger archive-link" onClick={() => { if (window.confirm('Lưu trữ mục học/nghiên cứu này trong dữ liệu demo?')) { archive('learning', item.id); navigate('/learning') } }}>Lưu trữ nội dung</button></div></div>
    {editing && <Modal title="Chỉnh sửa học/nghiên cứu" onClose={() => setEditing(false)} wide><LearningForm initial={item} onClose={() => setEditing(false)} /></Modal>}
    {newKnowledge && <Modal title="Lưu bài học vào kho kiến thức" onClose={() => setNewKnowledge(false)} wide><KnowledgeForm defaults={{ title: `Bài học từ: ${item.title}`, content: item.notes, category: 'insight', projectId: item.projectId, learningId: item.id }} onClose={() => setNewKnowledge(false)} onSaved={newId => navigate(`/knowledge/${newId}`)} /></Modal>}
  </>
}

export function KnowledgePage() {
  const { state } = useDemo(); const navigate = useNavigate(); const [modal, setModal] = useState(false)
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('all'); const [review, setReview] = useState('all')
  const items = state.knowledge.filter(item => !item.archived).filter(item => (category === 'all' || item.category === category) && (review === 'all' || item.reviewStatus === review) && (!query || normalise(`${item.title} ${item.content} ${item.tags.join(' ')}`).includes(normalise(query))))
  return <><PageHeading eyebrow="GIỮ LẠI ĐIỀU CÓ THỂ TÁI DÙNG" title="Kho kiến thức" description="Bài học, quy trình, prompt, mẫu và ghi nhận nghiên cứu có nguồn và trạng thái rà soát." action={<button className="button primary" onClick={() => setModal(true)}><Plus size={17}/> Thêm kiến thức</button>} />
    <div className="hub-stats"><Card><span className="hub-stat-icon blue"><Lightbulb size={19}/></span><strong>{state.knowledge.filter(item => !item.archived).length}</strong><small>Mục kiến thức</small></Card><Card><span className="hub-stat-icon orange"><BookOpen size={19}/></span><strong>{state.knowledge.filter(item => !item.archived && item.reviewStatus === 'draft').length}</strong><small>Chưa kiểm chứng</small></Card><Card><span className="hub-stat-icon navy"><FolderKanban size={19}/></span><strong>{new Set(state.knowledge.filter(item => !item.archived && item.projectId).map(item => item.projectId)).size}</strong><small>Dự án có kiến thức</small></Card></div>
    <Notice>Trạng thái “Đã rà soát” chỉ là nhãn trong dữ liệu minh họa, không thay thế việc kiểm chứng nguồn khi dùng thật.</Notice>
    <div className="hub-filters"><div className="filter-search"><Search size={17}/><input aria-label="Tìm trong kho kiến thức" placeholder="Tìm tiêu đề, nội dung, từ khóa..." value={query} onChange={e => setQuery(e.target.value)}/></div><select aria-label="Lọc nhóm kiến thức" value={category} onChange={e => setCategory(e.target.value)}><option value="all">Mọi nhóm</option>{Object.entries(knowledgeCategoryLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select aria-label="Lọc trạng thái rà soát kiến thức" value={review} onChange={e => setReview(e.target.value)}><option value="all">Mọi trạng thái</option>{Object.entries(reviewStatusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>
    <div className="hub-count">{items.length} mục trong bộ lọc</div><div className="hub-grid">{items.map(item => { const project = state.projects.find(p => p.id === item.projectId); return <Link className="hub-card" to={`/knowledge/${item.id}`} key={item.id}><div className="hub-card-top"><span className="hub-type">{knowledgeCategoryLabel[item.category]}</span><span className={`hub-status ${item.reviewStatus}`}>{reviewStatusLabel[item.reviewStatus]}</span></div><h2>{item.title}</h2><p>{item.content}</p><div className="hub-tags">{item.tags.slice(0, 3).map(tag => <span key={tag}>#{tag}</span>)}</div><div className="hub-card-foot"><span>{project?.title || 'Kiến thức chung'}</span><span>{dateLabel(item.updatedAt)} <ArrowRight size={16}/></span></div></Link> })}</div>
    {!items.length && <Card><Empty title="Không có mục kiến thức phù hợp" description="Thử từ khóa khác hoặc thêm một bài học mới." /></Card>}
    {modal && <Modal title="Thêm kiến thức" onClose={() => setModal(false)} wide><KnowledgeForm onClose={() => setModal(false)} onSaved={id => navigate(`/knowledge/${id}`)} /></Modal>}
  </>
}

export function KnowledgeDetailPage() {
  const { id } = useParams(); const { state, archive } = useDemo(); const navigate = useNavigate(); const [editing, setEditing] = useState(false)
  const item = state.knowledge.find(entry => entry.id === id && !entry.archived); if (!item) return <Missing name="kiến thức" to="/knowledge" />
  const project = state.projects.find(p => p.id === item.projectId); const customer = state.customers.find(c => c.id === item.customerId); const learning = state.learning.find(l => l.id === item.learningId)
  return <><Back to="/knowledge" label="Kho kiến thức" /><PageHeading eyebrow={`${knowledgeCategoryLabel[item.category]} · ${reviewStatusLabel[item.reviewStatus]}`} title={item.title} description={`Cập nhật ${dateLabel(item.updatedAt)}`} action={<button className="button outline" onClick={() => setEditing(true)}>Chỉnh sửa</button>} />
    <div className="detail-grid"><Card title="Nội dung kiến thức"><p className="hub-prose">{item.content}</p><div className="hub-tags">{item.tags.map(tag => <span key={tag}>#{tag}</span>)}</div></Card><div className="stack"><Card title="Nguồn & liên kết"><div className="hub-link-list">{project && <Link to={`/projects/${project.id}`}><FolderKanban size={17}/><span><strong>{project.title}</strong><small>Dự án</small></span><ArrowRight size={16}/></Link>}{customer && <Link to={`/customers/${customer.id}`}><FileText size={17}/><span><strong>{customer.name}</strong><small>Khách hàng</small></span><ArrowRight size={16}/></Link>}{learning && <Link to={`/learning/${learning.id}`}><BookOpen size={17}/><span><strong>{learning.title}</strong><small>Học/nghiên cứu</small></span><ArrowRight size={16}/></Link>}{safeSource(item.sourceUrl) && <a href={safeSource(item.sourceUrl)} target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/><span><strong>Mở nguồn</strong><small>{item.sourceUrl}</small></span><ArrowRight size={16}/></a>}{!project && !customer && !learning && !item.sourceUrl && <Empty title="Chưa có nguồn hoặc liên kết" />}</div></Card><Card title="Tình trạng"><Meta>{reviewStatusLabel[item.reviewStatus]}</Meta><p className="muted hub-mini-note">Nội dung demo; hãy kiểm chứng nguồn trước khi dùng vào tài liệu chính thức.</p></Card><button className="text-button danger archive-link" onClick={() => { if (window.confirm('Lưu trữ mục kiến thức này trong dữ liệu demo?')) { archive('knowledge', item.id); navigate('/knowledge') } }}>Lưu trữ kiến thức</button></div></div>
    {editing && <Modal title="Chỉnh sửa kiến thức" onClose={() => setEditing(false)} wide><KnowledgeForm initial={item} onClose={() => setEditing(false)} /></Modal>}
  </>
}

export function DataPage() {
  const { state, exportDemo } = useDemo(); const toast = useToast(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const [modal, setModal] = useState(false)
  const projectId = params.get('project') || ''; const [query, setQuery] = useState(''); const [kind, setKind] = useState('all')
  const assets = state.dataAssets.filter(item => !item.archived && (!projectId || item.projectId === projectId) && (kind === 'all' || item.kind === kind) && (!query || normalise(`${item.title} ${item.description} ${item.content} ${item.format}`).includes(normalise(query))))
  const projectDocs = state.projects.filter(p => !p.archived && (!projectId || p.id === projectId)).flatMap(p => p.documents.map(doc => ({ ...doc, project: p })))
  const projects = state.projects.filter(p => !p.archived)
  const selectedProject = projects.find(p => p.id === projectId)
  const projectNotes = state.notes.filter(item => !item.archived && item.projectId === projectId)
  const projectKnowledge = state.knowledge.filter(item => !item.archived && item.projectId === projectId)
  const projectTasks = state.tasks.filter(item => !item.archived && item.projectId === projectId)
  return <><PageHeading eyebrow="MỘT NƠI TRA CỨU TOÀN DỰ ÁN" title="Dữ liệu dự án" description="Tài sản dữ liệu, tài liệu, ghi chú và kiến thức của các dự án trong một màn hình." action={<button className="button primary" onClick={() => setModal(true)}><Plus size={17}/> Thêm dữ liệu</button>} />
    <Notice>Bản thử lưu văn bản và liên kết trên trình duyệt; chưa tải tệp lên server hay đồng bộ Drive. Không nhập dữ liệu thật/nhạy cảm.</Notice>
    <div className="hub-stats"><Card><span className="hub-stat-icon blue"><FolderKanban size={19}/></span><strong>{projects.length}</strong><small>Dự án</small></Card><Card><span className="hub-stat-icon orange"><Database size={19}/></span><strong>{state.dataAssets.filter(item => !item.archived).length}</strong><small>Tài sản dữ liệu</small></Card><Card><span className="hub-stat-icon navy"><Lightbulb size={19}/></span><strong>{state.knowledge.filter(item => !item.archived && item.projectId).length}</strong><small>Kiến thức gắn dự án</small></Card></div>
    <Card title="Tổng quan từng dự án"><div className="project-data-grid">{projects.map(project => { const taskCount = state.tasks.filter(t => !t.archived && t.projectId === project.id).length; const noteCount = state.notes.filter(n => !n.archived && n.projectId === project.id).length; const knowledgeCount = state.knowledge.filter(k => !k.archived && k.projectId === project.id).length; const assetCount = state.dataAssets.filter(a => !a.archived && a.projectId === project.id).length; return <button className={`project-data-card ${projectId === project.id ? 'selected' : ''}`} onClick={() => setParams(projectId === project.id ? {} : { project: project.id })} key={project.id}><strong>{project.title}</strong><span>{taskCount} việc · {noteCount} ghi chú</span><small>{knowledgeCount} kiến thức · {assetCount} dữ liệu · {project.documents.length} liên kết tệp</small></button> })}</div></Card>
    <div className="hub-section-head"><div><h2>Tài sản dữ liệu</h2><p>{projectId ? `Đang xem ${projects.find(p => p.id === projectId)?.title || 'dự án'}` : 'Tất cả dự án và dữ liệu dùng chung'}</p></div><button className="button outline" onClick={() => { exportDemo(); toast('Đã tải JSON chứa toàn bộ dữ liệu demo của ứng dụng.') }}><Download size={16}/> Xuất toàn bộ JSON</button></div>
    <div className="hub-filters"><div className="filter-search"><Search size={17}/><input aria-label="Tìm dữ liệu dự án" placeholder="Tìm tên, mô tả, nội dung dữ liệu..." value={query} onChange={e => setQuery(e.target.value)}/></div><select aria-label="Lọc loại dữ liệu" value={kind} onChange={e => setKind(e.target.value)}><option value="all">Mọi loại</option>{Object.entries(dataKindLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select aria-label="Lọc dự án dữ liệu" value={projectId} onChange={e => setParams(e.target.value ? { project: e.target.value } : {})}><option value="">Mọi dự án</option>{projects.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></div>
    <div className="hub-count">{assets.length} tài sản trong bộ lọc</div><div className="hub-grid">{assets.map(item => { const project = projects.find(p => p.id === item.projectId); return <Link className="hub-card" to={`/data/${item.id}`} key={item.id}><div className="hub-card-top"><span className="hub-type">{dataKindLabel[item.kind]}</span><span className={`hub-status ${item.reviewStatus}`}>{reviewStatusLabel[item.reviewStatus]}</span></div><h2>{item.title}</h2><p>{item.description}</p><div className="hub-tags"><span>{item.format || 'Chưa ghi định dạng'}</span></div><div className="hub-card-foot"><span>{project?.title || 'Dùng chung'}</span><span>{dateLabel(item.updatedAt)} <ArrowRight size={16}/></span></div></Link> })}</div>
    {!assets.length && <Card><Empty title="Chưa có dữ liệu ở bộ lọc này" description="Thêm một tài sản hoặc chọn dự án khác." /></Card>}
    <Card title="Liên kết tài liệu đã có trong hồ sơ dự án">{projectDocs.length ? <div className="hub-link-list">{projectDocs.map(doc => <a key={`${doc.project.id}-${doc.id}`} href={safeSource(doc.url) || '#'} target="_blank" rel="noopener noreferrer"><FileText size={17}/><span><strong>{doc.title}</strong><small>{doc.project.title}</small></span><ExternalLink size={16}/></a>)}</div> : <Empty title="Dự án này chưa có liên kết tài liệu" />}</Card>
    {selectedProject && <div className="detail-grid hub-project-context"><div className="stack"><Card title="Ghi chú & kiến thức của dự án">{projectKnowledge.length ? <div className="hub-link-list">{projectKnowledge.map(item => <Link to={`/knowledge/${item.id}`} key={item.id}><Lightbulb size={17}/><span><strong>{item.title}</strong><small>{reviewStatusLabel[item.reviewStatus]}</small></span><ArrowRight size={16}/></Link>)}</div> : <Empty title="Chưa có kiến thức gắn dự án" />}{projectNotes.map(note => <div className="note-tile" key={note.id}><span>{dateLabel(note.createdAt)} · Ghi chú</span><strong>{note.title}</strong><p>{note.content}</p></div>)}</Card></div><div className="stack"><Card title="Công việc & cam kết">{projectTasks.length ? projectTasks.map(task => <TaskRow key={task.id} task={task} compact />) : <Empty title="Chưa có việc trong dự án" />}</Card><Link className="button outline" to={`/projects/${selectedProject.id}`}>Mở hồ sơ dự án <ArrowRight size={16}/></Link></div></div>}
    {modal && <Modal title="Thêm tài sản dữ liệu" onClose={() => setModal(false)} wide><DataAssetForm defaults={{ projectId }} onClose={() => setModal(false)} onSaved={id => navigate(`/data/${id}`)} /></Modal>}
  </>
}

export function DataDetailPage() {
  const { id } = useParams(); const { state, archive } = useDemo(); const navigate = useNavigate(); const [editing, setEditing] = useState(false)
  const item = state.dataAssets.find(entry => entry.id === id && !entry.archived); if (!item) return <Missing name="tài sản dữ liệu" to="/data" />
  const project = state.projects.find(p => p.id === item.projectId); const customer = state.customers.find(c => c.id === item.customerId)
  return <><Back to={item.projectId ? `/data?project=${item.projectId}` : '/data'} label="Dữ liệu dự án" /><PageHeading eyebrow={`${dataKindLabel[item.kind]} · ${reviewStatusLabel[item.reviewStatus]}`} title={item.title} description={item.description} action={<button className="button outline" onClick={() => setEditing(true)}>Chỉnh sửa</button>} />
    <div className="detail-grid"><div className="stack"><Card title="Nội dung / cấu trúc"><p className="hub-prose">{item.content || 'Chưa có nội dung văn bản. Mở nguồn hoặc bổ sung mô tả khi chỉnh sửa.'}</p></Card><Notice>Tài sản này là dữ liệu minh họa lưu ở trình duyệt. Tệp thật chưa được tải lên.</Notice></div><div className="stack"><Card title="Nguồn & bối cảnh"><div className="detail-fields"><div><span>Định dạng</span><strong>{item.format || 'Chưa ghi'}</strong></div><div><span>Rà soát</span><strong>{reviewStatusLabel[item.reviewStatus]}</strong></div></div><div className="hub-link-list">{project && <Link to={`/projects/${project.id}`}><FolderKanban size={17}/><span><strong>{project.title}</strong><small>Dự án liên quan</small></span><ArrowRight size={16}/></Link>}{customer && <Link to={`/customers/${customer.id}`}><FileText size={17}/><span><strong>{customer.name}</strong><small>Khách hàng</small></span><ArrowRight size={16}/></Link>}{safeSource(item.sourceUrl) && <a href={safeSource(item.sourceUrl)} target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/><span><strong>Mở liên kết nguồn</strong><small>{item.sourceUrl}</small></span><ArrowRight size={16}/></a>}</div></Card><button className="text-button danger archive-link" onClick={() => { if (window.confirm('Lưu trữ tài sản dữ liệu này trong bản demo?')) { archive('dataAssets', item.id); navigate('/data') } }}>Lưu trữ dữ liệu</button></div></div>
    {editing && <Modal title="Chỉnh sửa tài sản dữ liệu" onClose={() => setEditing(false)} wide><DataAssetForm initial={item} onClose={() => setEditing(false)} /></Modal>}
  </>
}
