import { useMemo, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router'
import { ArrowLeft, ArrowRight, BookOpen, Bot, CalendarDays, Check, ChevronLeft, ChevronRight, CircleAlert, Database, Download, ExternalLink, FileText, FolderKanban, Lightbulb, Mail, Plus, RotateCcw, Search, ShieldCheck, Sparkles, Trash2, Upload, Users } from 'lucide-react'
import type { AIProposal, AIProposalItem, CalendarEventLink } from './domain'
import { b2bStages, b2cStages, isOpenTask, projectStatusLabel } from './domain'
import { NoteForm, OpportunityForm, ProjectForm, TaskForm } from './forms'
import { useDemo } from './store'
import { Card, Empty, Field, Modal, Notice, PageHeading, SectionHeading, TaskRow, useToast } from './ui'
import { addDays, currency, dateLabel, dateTimeLabel, normalise, relativeLabel, startOfWeek, todayISO, uid } from './utils'

const Back=({to,label}:{to:string;label:string})=><Link className="back-link" to={to}><ArrowLeft size={16}/>{label}</Link>
const Missing=({name,to}:{name:string;to:string})=><div className="not-found"><h1>Không tìm thấy {name}</h1><Link className="button primary" to={to}>Quay lại danh sách</Link></div>

export function OpportunitiesPage(){
  const {state}=useDemo();const [type,setType]=useState<'B2B'|'B2C'>('B2B');const [modal,setModal]=useState(false);const navigate=useNavigate()
  const stages=type==='B2B'?b2bStages:b2cStages
  const opps=state.opportunities.filter(o=>!o.archived&&o.customerType===type)
  return <><PageHeading eyebrow="TỪ NHU CẦU ĐẾN HỢP TÁC" title="Cơ hội" description="Theo dõi bước tiếp theo riêng cho khách doanh nghiệp và cá nhân." action={<button className="button primary" onClick={()=>setModal(true)}><Plus size={17}/> Tạo cơ hội</button>}/>
    <div className="tabs"><button className={type==='B2B'?'active':''} onClick={()=>setType('B2B')}>Doanh nghiệp B2B</button><button className={type==='B2C'?'active':''} onClick={()=>setType('B2C')}>Cá nhân / SME</button></div>
    <Notice>Pipeline đang dùng trạng thái minh họa; các bước bán hàng sẽ được chốt trước khi nối dữ liệu thật.</Notice>
    <div className="pipeline">{stages.map(stage=>{const items=opps.filter(o=>o.stage===stage);return <div className="pipeline-col" key={stage}><div className="pipeline-head"><h2>{stage}</h2><span>{items.length}</span></div><div className="pipeline-items">{items.map(o=>{const c=state.customers.find(c=>c.id===o.customerId);return <Link to={`/opportunities/${o.id}`} className="opportunity-card" key={o.id}><span className="eyebrow">{o.product||'CHƯA PHÂN LOẠI'}</span><strong>{o.title}</strong><small>{c?.name||'Khách chưa rõ'}</small><div><span><CalendarDays size={14}/>{relativeLabel(o.nextActionAt)}</span><ArrowRight size={16}/></div></Link>})}{!items.length&&<div className="pipeline-empty">Chưa có cơ hội</div>}</div></div>})}</div>
    {modal&&<Modal title="Tạo cơ hội" onClose={()=>setModal(false)} wide><OpportunityForm onClose={()=>setModal(false)} onSaved={id=>navigate(`/opportunities/${id}`)}/></Modal>}
  </>
}

export function OpportunityDetailPage(){
  const {id}=useParams();const {state,update,archive,add}=useDemo();const toast=useToast();const navigate=useNavigate();const [editing,setEditing]=useState(false);const [reason,setReason]=useState('')
  const opp=state.opportunities.find(o=>o.id===id&&!o.archived);if(!opp)return <Missing name="cơ hội" to="/opportunities"/>
  const customer=state.customers.find(c=>c.id===opp.customerId);const projects=state.projects.filter(p=>p.opportunityId===opp.id&&!p.archived)
  const tasks=state.tasks.filter(t=>t.opportunityId===opp.id&&!t.archived);const stages=opp.customerType==='B2C'?b2cStages:b2bStages
  const moveStage=(value:string)=>{if(value==='Tạm dừng'||value==='Không phù hợp'||value==='Chưa phù hợp'){const why=window.prompt('Ghi lý do để sau này còn hiểu bối cảnh:',reason);if(why===null)return;setReason(why);update('opportunities',opp.id,{stage:value,reason:why})}else update('opportunities',opp.id,{stage:value});toast('Đã cập nhật giai đoạn trong dữ liệu demo.')}
  const createProject=()=>{if(projects.length){navigate(`/projects/${projects[0].id}`);return}const item=add('projects',{title:opp.title,type:opp.product||'Đào tạo',status:'planning',customerId:opp.customerId,opportunityId:opp.id,objective:opp.nextAction||'Chốt mục tiêu và đầu ra triển khai',ownerId:'u1',milestones:[],documents:[]});update('opportunities',opp.id,{stage:opp.customerType==='B2B'?'Triển khai':'Đã đăng ký'});toast('Đã tạo dự án minh họa từ cơ hội.');navigate(`/projects/${item.id}`)}
  return <><Back to="/opportunities" label="Danh sách cơ hội"/><PageHeading eyebrow={`${opp.customerType} · ${opp.product}`} title={opp.title} description={customer?.name||'Khách chưa rõ'} action={<div className="button-group"><button className="button outline" onClick={()=>setEditing(true)}>Chỉnh sửa</button><button className="button primary" onClick={createProject}>{projects.length?'Mở dự án':'Tạo dự án'} <ArrowRight size={16}/></button></div>}/>
    <div className="detail-grid"><div className="stack"><Card title="Hành trình cơ hội"><div className="stage-list">{stages.map((stage,index)=><button className={`stage-step ${stage===opp.stage?'current':''}`} key={stage} onClick={()=>moveStage(stage)}><span>{index+1}</span><strong>{stage}</strong>{stage===opp.stage&&<Check size={17}/>}</button>)}</div></Card><Card><SectionHeading title="Việc cần làm" link={`/tasks?view=all`}/>{tasks.length?tasks.map(t=><TaskRow key={t.id} task={t} compact/>):<Empty title="Cơ hội chưa có việc gắn trực tiếp"/>}</Card></div>
      <div className="stack"><Card title="Bước tiếp theo"><div className="next-action"><strong>{opp.nextAction||'Chưa có bước tiếp theo'}</strong><span><CalendarDays size={16}/>{dateLabel(opp.nextActionAt)}</span></div><div className="detail-fields"><div><span>Giai đoạn</span><strong>{opp.stage}</strong></div><div><span>Giá trị dự kiến</span><strong>{currency(opp.value)}</strong></div><div><span>Người phụ trách</span><strong>{state.users.find(u=>u.id===opp.ownerId)?.name||'Chưa rõ'}</strong></div>{opp.reason&&<div><span>Lý do ghi nhận</span><strong>{opp.reason}</strong></div>}</div></Card><Card title="Liên kết hồ sơ"><div className="linked-list">{customer&&<Link to={`/customers/${customer.id}`}><Users size={18}/><span><small>KHÁCH HÀNG</small>{customer.name}</span><ArrowRight size={16}/></Link>}{projects.map(p=><Link key={p.id} to={`/projects/${p.id}`}><FolderKanban size={18}/><span><small>DỰ ÁN TRIỂN KHAI</small>{p.title}</span><ArrowRight size={16}/></Link>)}</div></Card><button className="text-button danger archive-link" onClick={()=>{if(window.confirm('Lưu trữ cơ hội này trong dữ liệu demo?')){archive('opportunities',opp.id);navigate('/opportunities')}}}>Lưu trữ cơ hội</button></div></div>
    {editing&&<Modal title="Chỉnh sửa cơ hội" onClose={()=>setEditing(false)} wide><OpportunityForm initial={opp} onClose={()=>setEditing(false)}/></Modal>}
  </>
}

export function ProjectsPage(){
  const {state}=useDemo();const navigate=useNavigate();const [modal,setModal]=useState(false);const [filter,setFilter]=useState('all')
  const items=state.projects.filter(p=>!p.archived&&(filter==='all'||p.status===filter)).sort((a,b)=>(a.nextMilestoneAt||'9999').localeCompare(b.nextMilestoneAt||'9999'))
  return <><PageHeading eyebrow="TỪ CAM KẾT ĐẾN BÀN GIAO" title="Dự án" description="Mục tiêu, mốc tiếp theo, công việc và tài liệu của từng chương trình." action={<button className="button primary" onClick={()=>setModal(true)}><Plus size={17}/> Tạo dự án</button>}/>
    <div className="tabs"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Tất cả</button>{Object.entries(projectStatusLabel).map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div>
    <div className="project-grid">{items.map(p=>{const customer=state.customers.find(c=>c.id===p.customerId);const tasks=state.tasks.filter(t=>t.projectId===p.id&&!t.archived);const done=tasks.filter(t=>t.status==='done').length;return <Link className="project-card" to={`/projects/${p.id}`} key={p.id}><div className="project-card-top"><span className="project-type">{p.type}</span><span className={`badge project-${p.status}`}>{projectStatusLabel[p.status]}</span></div><h2>{p.title}</h2><p>{p.objective}</p><div className="project-card-meta"><span>{customer?.name||'Dự án nội bộ'}</span><span>Mốc: {relativeLabel(p.nextMilestoneAt)}</span></div><div className="progress-track"><div style={{width:`${tasks.length?done/tasks.length*100:0}%`}}/></div><div className="project-card-bottom"><span>{done}/{tasks.length} việc hoàn thành</span><ArrowRight size={17}/></div></Link>})}</div>{!items.length&&<Card><Empty title="Không có dự án ở trạng thái này"/></Card>}
    {modal&&<Modal title="Tạo dự án" onClose={()=>setModal(false)} wide><ProjectForm onClose={()=>setModal(false)} onSaved={id=>navigate(`/projects/${id}`)}/></Modal>}
  </>
}

export function ProjectDetailPage(){
  const {id}=useParams();const {state,update,archive}=useDemo();const toast=useToast();const navigate=useNavigate();const [editing,setEditing]=useState(false);const [taskModal,setTaskModal]=useState(false);const [noteModal,setNoteModal]=useState(false)
  const [milestoneTitle,setMilestoneTitle]=useState('');const [milestoneDate,setMilestoneDate]=useState('');const [docTitle,setDocTitle]=useState('');const [docUrl,setDocUrl]=useState('');const [selectedFile,setSelectedFile]=useState('')
  const project=state.projects.find(p=>p.id===id&&!p.archived);if(!project)return <Missing name="dự án" to="/projects"/>
  const customer=state.customers.find(c=>c.id===project.customerId);const opp=state.opportunities.find(o=>o.id===project.opportunityId)
  const tasks=state.tasks.filter(t=>t.projectId===project.id&&!t.archived);const notes=state.notes.filter(n=>n.projectId===project.id&&!n.archived)
  const projectKnowledge=state.knowledge.filter(k=>k.projectId===project.id&&!k.archived)
  const projectData=state.dataAssets.filter(a=>a.projectId===project.id&&!a.archived)
  const projectLearning=state.learning.filter(l=>l.projectId===project.id&&!l.archived)
  const done=tasks.filter(t=>t.status==='done').length
  const addMilestone=(event:FormEvent)=>{event.preventDefault();if(!milestoneTitle.trim()||!milestoneDate)return;const milestones=[...project.milestones,{id:uid(),title:milestoneTitle.trim(),date:milestoneDate,status:'todo' as const,ownerId:'u1'}];update('projects',project.id,{milestones,nextMilestoneAt:milestones.filter(m=>m.status==='todo').map(m=>m.date).sort()[0]});setMilestoneTitle('');setMilestoneDate('');toast('Đã thêm mốc vào dữ liệu demo.')}
  const toggleMilestone=(milestoneId:string)=>{const milestones=project.milestones.map(m=>m.id===milestoneId?{...m,status:m.status==='done'?'todo' as const:'done' as const}:m);update('projects',project.id,{milestones,nextMilestoneAt:milestones.filter(m=>m.status==='todo').map(m=>m.date).sort()[0]});toast('Đã cập nhật mốc.')}
  const addDoc=(event:FormEvent)=>{event.preventDefault();if(!docTitle.trim()||!/^https?:\/\//i.test(docUrl)){toast('Hãy nhập tên và đường dẫn http/https hợp lệ.');return}update('projects',project.id,{documents:[...project.documents,{id:uid(),title:docTitle.trim(),url:docUrl,addedAt:todayISO()}]});setDocTitle('');setDocUrl('');toast('Đã lưu liên kết tài liệu vào dữ liệu demo.')}
  return <><Back to="/projects" label="Danh sách dự án"/><PageHeading eyebrow={`${project.type} · ${projectStatusLabel[project.status]}`} title={project.title} description={project.objective} action={<div className="button-group"><button className="button outline" onClick={()=>setEditing(true)}>Chỉnh sửa</button><button className="button primary" onClick={()=>setTaskModal(true)}><Plus size={16}/> Thêm việc</button></div>}/>
    <div className="project-summary"><div><span>KHÁCH HÀNG</span>{customer?<Link to={`/customers/${customer.id}`}>{customer.name}</Link>:<strong>Dự án nội bộ</strong>}</div><div><span>CƠ HỘI NGUỒN</span>{opp?<Link to={`/opportunities/${opp.id}`}>{opp.title}</Link>:<strong>Không có</strong>}</div><div><span>MỐC TIẾP THEO</span><strong>{dateLabel(project.nextMilestoneAt)}</strong></div><div><span>TIẾN ĐỘ VIỆC</span><strong>{done}/{tasks.length} hoàn thành</strong></div></div>
    <div className="detail-grid"><div className="stack"><Card><SectionHeading title="Công việc"/><div className="inline-actions"><button className="button small outline" onClick={()=>setTaskModal(true)}>+ Thêm việc</button></div>{tasks.length?tasks.map(t=><TaskRow key={t.id} task={t} compact/>):<Empty title="Chưa có việc trong dự án"/>}</Card>
      <Card><SectionHeading title="Ghi chú & quyết định"><button className="text-button" onClick={()=>setNoteModal(true)}>+ Ghi chú</button></SectionHeading>{notes.map(n=><div className="note-tile" key={n.id}><span>{dateLabel(n.createdAt)}</span><strong>{n.title}</strong><p>{n.content}</p></div>)}{!notes.length&&<Empty title="Chưa có ghi chú"/>}</Card></div>
      <div className="stack"><Card title="Mốc triển khai"><div className="milestone-list">{project.milestones.map(m=><button className={`milestone ${m.status==='done'?'done':''}`} key={m.id} onClick={()=>toggleMilestone(m.id)}><span className="milestone-check">{m.status==='done'?<Check size={15}/>:null}</span><span><strong>{m.title}</strong><small>{dateLabel(m.date)}</small></span></button>)}</div><form className="mini-form" onSubmit={addMilestone}><input value={milestoneTitle} onChange={e=>setMilestoneTitle(e.target.value)} placeholder="Tên mốc mới" aria-label="Tên mốc mới"/><input type="date" value={milestoneDate} onChange={e=>setMilestoneDate(e.target.value)} aria-label="Ngày mốc mới"/><button className="button small outline" type="submit">+ Thêm mốc</button></form></Card>
      <Card title="Kiến thức & dữ liệu dự án"><div className="hub-link-list">{projectLearning.slice(0,2).map(item=><Link key={item.id} to={`/learning/${item.id}`}><BookOpen size={17}/><span><strong>{item.title}</strong><small>Học/nghiên cứu · {item.progress}%</small></span><ArrowRight size={16}/></Link>)}{projectKnowledge.slice(0,3).map(item=><Link key={item.id} to={`/knowledge/${item.id}`}><Lightbulb size={17}/><span><strong>{item.title}</strong><small>Kiến thức · {item.reviewStatus==='reviewed'?'Đã rà soát':'Chưa kiểm chứng'}</small></span><ArrowRight size={16}/></Link>)}{projectData.slice(0,3).map(item=><Link key={item.id} to={`/data/${item.id}`}><Database size={17}/><span><strong>{item.title}</strong><small>Dữ liệu · {item.format||'Chưa rõ định dạng'}</small></span><ArrowRight size={16}/></Link>)}</div><Link className="text-link" to={`/data?project=${project.id}`}>Xem toàn bộ dữ liệu dự án <ArrowRight size={15}/></Link></Card>
      <Card title="Tài liệu liên quan">{project.documents.map(doc=><a className="linked-tile" key={doc.id} href={doc.url} target="_blank" rel="noopener noreferrer"><FileText size={18}/><div><strong>{doc.title}</strong><small>Đường dẫn minh họa · {dateLabel(doc.addedAt)}</small></div><ExternalLink size={15}/></a>)}<form className="mini-form" onSubmit={addDoc}><input value={docTitle} onChange={e=>setDocTitle(e.target.value)} placeholder="Tên tài liệu" aria-label="Tên tài liệu"/><input value={docUrl} onChange={e=>setDocUrl(e.target.value)} placeholder="https://..." aria-label="Đường dẫn tài liệu"/><button className="button small outline" type="submit">+ Lưu liên kết</button></form><div className="file-demo"><label><Upload size={16}/> Chọn tệp để xem tên<input type="file" onChange={e=>setSelectedFile(e.target.files?.[0]?.name||'')}/></label>{selectedFile&&<small>Đã chọn: {selectedFile}. Bản thử chưa lưu tệp.</small>}</div></Card><button className="text-button danger archive-link" onClick={()=>{if(window.confirm('Lưu trữ dự án này trong dữ liệu demo?')){archive('projects',project.id);navigate('/projects')}}}>Lưu trữ dự án</button></div></div>
    {editing&&<Modal title="Chỉnh sửa dự án" onClose={()=>setEditing(false)} wide><ProjectForm initial={project} onClose={()=>setEditing(false)}/></Modal>}
    {taskModal&&<Modal title="Tạo việc trong dự án" onClose={()=>setTaskModal(false)} wide><TaskForm defaults={{projectId:project.id,customerId:project.customerId,opportunityId:project.opportunityId}} onClose={()=>setTaskModal(false)}/></Modal>}
    {noteModal&&<Modal title="Ghi chú dự án" onClose={()=>setNoteModal(false)} wide><NoteForm defaults={{projectId:project.id,customerId:project.customerId}} onClose={()=>setNoteModal(false)}/></Modal>}
  </>
}

export function CalendarPage(){
  const {state,update}=useDemo();const toast=useToast();const [date,setDate]=useState(todayISO());const [selected,setSelected]=useState<CalendarEventLink|null>(null)
  const weekStart=startOfWeek(date);const days=Array.from({length:7},(_,i)=>addDays(weekStart,i))
  const [customerId,setCustomerId]=useState('');const [projectId,setProjectId]=useState('')
  const open=(event:CalendarEventLink)=>{setSelected(event);setCustomerId(event.customerId||'');setProjectId(event.projectId||'')}
  const saveLink=()=>{if(!selected)return;update('events',selected.id,{customerId:customerId||undefined,projectId:projectId||undefined});setSelected(null);toast('Đã lưu liên kết sự kiện trong dữ liệu minh họa; Google Calendar không thay đổi.')}
  return <><PageHeading eyebrow="KẾ HOẠCH THEO THỜI GIAN" title="Lịch tuần" description="Cuộc hẹn và khoảng thời gian đã xếp cho công việc." action={<button className="button outline" onClick={()=>setDate(todayISO())}>Về hôm nay</button>}/>
    <Notice>Lịch minh họa · chưa kết nối Google. Thay đổi ở đây chỉ lưu trên trình duyệt này.</Notice>
    <div className="calendar-toolbar"><button className="icon-button" aria-label="Tuần trước" onClick={()=>setDate(addDays(date,-7))}><ChevronLeft size={20}/></button><strong>{dateLabel(weekStart)} – {dateLabel(days[6])}</strong><button className="icon-button" aria-label="Tuần sau" onClick={()=>setDate(addDays(date,7))}><ChevronRight size={20}/></button></div>
    <div className="calendar-week">{days.map((day,i)=>{const events=state.events.filter(e=>!e.archived&&e.start.slice(0,10)===day).sort((a,b)=>a.start.localeCompare(b.start));const scheduled=state.tasks.filter(t=>!t.archived&&t.scheduledStart?.slice(0,10)===day);return <div className={`calendar-day ${day===todayISO()?'is-today':''}`} key={day}><div className="calendar-day-head"><span>{['T2','T3','T4','T5','T6','T7','CN'][i]}</span><strong>{new Date(`${day}T12:00:00`).getDate()}</strong></div><div className="calendar-day-items">{events.map(e=><button key={e.id} className={`calendar-event ${e.cancelled?'cancelled':''}`} onClick={()=>open(e)}><small>{e.allDay?'Cả ngày':new Date(e.start).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</small><strong>{e.title}</strong><span>Cuộc hẹn{e.cancelled?' · Đã hủy':''}</span></button>)}{scheduled.map(t=><Link key={t.id} to={`/tasks/${t.id}`} className="calendar-event time-block"><small>{t.scheduledStart?.slice(11,16)}</small><strong>{t.title}</strong><span>Khối làm việc</span></Link>)}{!events.length&&!scheduled.length&&<span className="calendar-blank">Không có lịch</span>}</div></div>})}</div>
    {selected&&<Modal title="Cuộc hẹn minh họa" onClose={()=>setSelected(null)}><div className="form-grid"><div className="event-summary"><strong>{selected.title}</strong><span>{dateTimeLabel(selected.start)} · {selected.allDay?'Cả ngày':dateTimeLabel(selected.end)}</span>{selected.cancelled&&<Notice tone="warning">Sự kiện này đã hủy trong dữ liệu mẫu.</Notice>}</div><Field label="Gắn khách hàng"><select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Không gắn</option>{state.customers.filter(c=>!c.archived).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Gắn dự án"><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Không gắn</option>{state.projects.filter(p=>!p.archived).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></Field><div className="inline-actions">{selected.customerId&&<Link className="text-link" to={`/customers/${selected.customerId}`}>Mở hồ sơ khách <ArrowRight size={15}/></Link>}{selected.projectId&&<Link className="text-link" to={`/projects/${selected.projectId}`}>Mở dự án <ArrowRight size={15}/></Link>}</div><div className="form-actions"><button className="button ghost" onClick={()=>setSelected(null)}>Đóng</button><button className="button primary" onClick={saveLink}>Lưu liên kết demo</button></div></div></Modal>}
  </>
}

type AIAnswer={text:string;links:Array<{label:string;to:string}>}
const scenarios=[
  {id:'summary',label:'Tóm tắt Công ty An Phát',icon:Users},
  {id:'overdue',label:'Việc nào đang quá hạn?',icon:CircleAlert},
  {id:'call',label:'Từ cuộc gọi tạo việc',icon:Sparkles},
  {id:'meeting',label:'Chuẩn bị trước cuộc hẹn',icon:CalendarDays},
  {id:'project',label:'Tóm tắt dự án Sao Việt',icon:FolderKanban},
]
export function AIPage(){
  const {state,commitProposal}=useDemo();const [params]=useSearchParams();const inboxId=params.get('inbox')
  const [input,setInput]=useState('');const [answer,setAnswer]=useState<AIAnswer|null>(null);const [proposal,setProposal]=useState<AIProposal|null>(null);const [result,setResult]=useState('')
  const toast=useToast();const inbox=state.inbox.find(i=>i.id===inboxId)
  const makeItem=(kind:'task'|'note',title:string,content:string,customerId?:string,dueAt?:string,sourceInboxId?:string,sourceNoteId?:string):AIProposalItem=>({id:uid(),kind,title,content,customerId,dueAt,sourceInboxId,sourceNoteId,included:true})
  const choose=(id:string)=>{setResult('');setProposal(null)
    if(id==='summary'){
      const c=state.customers.find(c=>c.id==='c1');const notes=state.notes.filter(n=>n.customerId==='c1');const open=state.tasks.filter(t=>t.customerId==='c1'&&isOpenTask(t));
      setAnswer({text:`${c?.name||'Không tìm thấy'}: ${c?.need||''}. Có ${open.length} việc còn mở và ${notes.length} ghi chú. Lần liên hệ tiếp: ${relativeLabel(c?.nextContactAt)}.`,links:[{label:'Hồ sơ An Phát',to:'/customers/c1'},...open.slice(0,2).map(t=>({label:t.title,to:`/tasks/${t.id}`}))]});return
    }
    if(id==='overdue'){
      const open=state.tasks.filter(t=>isOpenTask(t)&&t.status!=='waiting'&&t.dueAt&&t.dueAt<todayISO())
      setAnswer({text:`Có ${open.length} việc quá hạn trong dữ liệu minh họa. Dưới đây là các việc đầu tiên cần mở để xem bối cảnh.`,links:open.slice(0,5).map(t=>({label:t.title,to:`/tasks/${t.id}`}))});return
    }
    if(id==='meeting'){
      const upcoming=state.events.filter(e=>!e.cancelled&&e.start.slice(0,10)>=todayISO()).sort((a,b)=>a.start.localeCompare(b.start))[0]
      const customer=state.customers.find(c=>c.id===upcoming?.customerId)
      setAnswer({text:upcoming?`Cuộc hẹn gần nhất: ${upcoming.title} lúc ${dateTimeLabel(upcoming.start)}. ${customer?`Khách: ${customer.name}. Nhu cầu: ${customer.need}.`:''}`:'Không có cuộc hẹn sắp tới.',links:customer?[{label:'Mở hồ sơ khách',to:`/customers/${customer.id}`},{label:'Xem lịch',to:'/calendar'}]:[{label:'Xem lịch',to:'/calendar'}]});return
    }
    if(id==='project'){
      const p=state.projects.find(p=>p.id==='p1');const tasks=state.tasks.filter(t=>t.projectId===p?.id&&isOpenTask(t))
      setAnswer({text:p?`${p.title}: ${projectStatusLabel[p.status]}. Mục tiêu: ${p.objective}. Mốc tiếp theo: ${dateLabel(p.nextMilestoneAt)}. Còn ${tasks.length} việc mở.`:'Không tìm thấy dự án.',links:p?[{label:'Mở dự án Sao Việt',to:`/projects/${p.id}`},...tasks.slice(0,2).map(t=>({label:t.title,to:`/tasks/${t.id}`}))]:[]});return
    }
    const source=inbox||state.inbox.find(i=>i.status==='new')
    const sourceNote=state.notes.find(n=>n.id==='n1')
    const proposalId=uid()
    setAnswer({text:'Bản mô phỏng đã chuẩn bị các mục dưới đây. Hãy kiểm tra tên khách và ngày cụ thể trước khi chốt. Các ngày chưa rõ được để trống.',links:source?[{label:'Mở Hộp ghi nhanh',to:'/inbox'}]:[{label:'Mở ghi chú nguồn ở hồ sơ An Phát',to:'/customers/c1'}]})
    setProposal({id:proposalId,sourceLabel:source?`Hộp ghi nhanh: ${source.content}`:`Ghi chú: ${sourceNote?.title||'cuộc gọi'}`,items:source?
      [makeItem('note','Ghi chú từ cuộc trao đổi',source.content,undefined,undefined,source.id),makeItem('task',source.content,`Phát sinh từ Hộp ghi nhanh: ${source.content}`,undefined,undefined,source.id)]:
      [makeItem('note','Tóm tắt cuộc gọi An Phát',sourceNote?.content||'', 'c1',undefined,undefined,'n1'),makeItem('task','Gửi đề cương cho An Phát','Theo cam kết trong ghi chú cuộc gọi.','c1',undefined,undefined,'n1'),makeItem('task','Hỏi lịch khảo sát An Phát','Xác nhận lịch với đầu mối khách hàng.','c1',undefined,undefined,'n1')]})
  }
  const custom=(event:FormEvent)=>{event.preventDefault();const matched=scenarios.find(s=>normalise(s.label)===normalise(input));if(matched){choose(matched.id);return}setProposal(null);setResult('');setAnswer({text:'Bản demo chỉ hỗ trợ các tình huống mẫu ở bên trái. Nội dung tự do chưa được gửi đến AI hay lưu vào hệ thống.',links:[]})}
  const updateItem=(id:string,patch:Partial<AIProposalItem>)=>setProposal(current=>current?{...current,items:current.items.map(item=>item.id===id?{...item,...patch}:item)}:null)
  const save=()=>{if(!proposal)return;const outcome=commitProposal(proposal);setResult(outcome.message);toast(outcome.message)}
  return <><PageHeading eyebrow="TRỢ LÝ CÓ BƯỚC DUYỆT" title="AI demo" description="Hỏi dữ liệu minh họa và thử quy trình xem, sửa, chốt bản nháp thay đổi."/><Notice>Đây là bản mô phỏng. Không có lời gọi model AI; câu hỏi ngoài kịch bản mẫu sẽ không được xử lý.</Notice>
    <div className="ai-layout"><Card className="ai-scenarios"><h2>Chọn một tình huống</h2><p>Thử theo dữ liệu mẫu hiện có.</p>{scenarios.map(({id,label,icon:Icon})=><button className="scenario-button" key={id} onClick={()=>choose(id)}><Icon size={19}/><span>{label}</span><ArrowRight size={16}/></button>)}{inbox&&<button className="scenario-button highlighted" onClick={()=>choose('call')}><Sparkles size={19}/><span>Tạo bản nháp từ mục đang chọn</span><ArrowRight size={16}/></button>}</Card>
      <div className="stack"><Card className="ai-chat"><div className="ai-chat-head"><span className="ai-orb"><Bot size={21}/></span><div><strong>VISUN AI Assistant</strong><small>Mô phỏng · chỉ đọc dữ liệu demo</small></div></div><div className="ai-chat-body">{!answer?<div className="ai-welcome"><Sparkles size={31}/><h2>Hôm nay anh cần xem gì?</h2><p>Chọn một tình huống để xem app có thể dẫn về đúng hồ sơ và chuẩn bị bản nháp như thế nào.</p></div>:<div className="ai-answer"><span className="ai-orb small"><Bot size={16}/></span><div><p>{answer.text}</p>{answer.links.length>0&&<div className="ai-sources"><strong>Nguồn trong dữ liệu demo</strong>{answer.links.map((link,i)=><Link key={i} to={link.to}>{link.label} <ArrowRight size={14}/></Link>)}</div>}</div></div>}</div><form className="ai-input" onSubmit={custom}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Chọn tình huống mẫu hoặc nhập để thử giới hạn demo" aria-label="Nhập câu hỏi AI demo"/><button className="button primary" type="submit" aria-label="Gửi câu hỏi"><ArrowRight size={18}/></button></form></Card>
      {proposal&&<Card className="proposal-panel"><div className="proposal-head"><div><span className="eyebrow">BẢN NHÁP THAY ĐỔI · MÔ PHỎNG</span><h2>Kiểm tra trước khi lưu</h2><p>{proposal.sourceLabel}</p></div><span className="count-pill">{proposal.items.filter(i=>i.included).length} mục</span></div>{proposal.items.map((item,index)=><div className={`proposal-item ${!item.included?'excluded':''}`} key={item.id}><label className="proposal-toggle"><input type="checkbox" checked={item.included} onChange={e=>updateItem(item.id,{included:e.target.checked})}/><strong>{index+1}. {item.kind==='task'?'Công việc':'Ghi chú'}</strong></label><Field label="Tên mục"><input value={item.title} onChange={e=>updateItem(item.id,{title:e.target.value})} disabled={!item.included}/></Field><Field label="Nội dung"><textarea rows={2} value={item.content} onChange={e=>updateItem(item.id,{content:e.target.value})} disabled={!item.included}/></Field><div className="form-two"><Field label="Khách hàng"><select value={item.customerId||''} onChange={e=>updateItem(item.id,{customerId:e.target.value||undefined})} disabled={!item.included}><option value="">Chưa xác định</option>{state.customers.filter(c=>!c.archived).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>{item.kind==='task'&&<Field label="Hạn cụ thể"><input type="date" value={item.dueAt||''} onChange={e=>updateItem(item.id,{dueAt:e.target.value||undefined})} disabled={!item.included}/></Field>}</div></div>)}<div className="proposal-footer"><p>Chỉ các mục được chọn mới lưu vào dữ liệu minh họa. Bấm lại sẽ không tạo trùng.</p><button className="button primary" onClick={save}><Check size={17}/> Chốt và lưu</button></div>{result&&<Notice tone={result.startsWith('Đã lưu')?'info':'warning'}>{result}</Notice>}</Card>}</div></div>
  </>
}

export function SearchPage(){
  const {state}=useDemo();const [params,setParams]=useSearchParams();const query=params.get('q')||'';const [input,setInput]=useState(query)
  const results=useMemo(()=>{
    if(!query.trim())return [] as Array<{type:string;title:string;description:string;to:string;date:string}>
    const q=normalise(query);const matches=(...values:(string|undefined)[])=>normalise(values.filter(Boolean).join(' ')).includes(q)
    return [
      ...state.customers.filter(c=>!c.archived&&matches(c.name,c.contactName,c.need)).map(c=>({type:'Khách hàng',title:c.name,description:c.need,to:`/customers/${c.id}`,date:c.updatedAt})),
      ...state.opportunities.filter(o=>!o.archived&&matches(o.title,o.product,o.nextAction)).map(o=>({type:'Cơ hội',title:o.title,description:o.nextAction,to:`/opportunities/${o.id}`,date:o.updatedAt})),
      ...state.projects.filter(p=>!p.archived&&matches(p.title,p.objective)).map(p=>({type:'Dự án',title:p.title,description:p.objective,to:`/projects/${p.id}`,date:p.updatedAt})),
      ...state.tasks.filter(t=>!t.archived&&matches(t.title,t.description)).map(t=>({type:'Công việc',title:t.title,description:t.description,to:`/tasks/${t.id}`,date:t.updatedAt})),
      ...state.notes.filter(n=>!n.archived&&matches(n.title,n.content)).map(n=>({type:'Ghi chú',title:n.title,description:n.content,to:n.customerId?`/customers/${n.customerId}`:n.projectId?`/projects/${n.projectId}`:'/inbox',date:n.updatedAt})),
      ...state.learning.filter(item=>!item.archived&&matches(item.title,item.objective,item.notes,item.nextAction)).map(item=>({type:'Học/nghiên cứu',title:item.title,description:item.objective,to:`/learning/${item.id}`,date:item.updatedAt})),
      ...state.knowledge.filter(item=>!item.archived&&matches(item.title,item.content,item.tags.join(' '))).map(item=>({type:'Kiến thức',title:item.title,description:item.content,to:`/knowledge/${item.id}`,date:item.updatedAt})),
      ...state.dataAssets.filter(item=>!item.archived&&matches(item.title,item.description,item.content,item.format)).map(item=>({type:'Dữ liệu dự án',title:item.title,description:item.description,to:`/data/${item.id}`,date:item.updatedAt})),
      ...state.content.filter(item=>!item.archived&&matches(item.title,item.angle,item.draft,item.sourceNote)).map(item=>({type:'Truyền thông',title:item.title,description:item.angle,to:`/content/${item.id}`,date:item.updatedAt})),
    ].sort((a,b)=>b.date.localeCompare(a.date))
  },[query,state])
  const submit=(event:FormEvent)=>{event.preventDefault();setParams(input?{q:input}:{})}
  return <><PageHeading eyebrow="TRUY TÌM BỐI CẢNH" title="Tìm kiếm" description="Tìm trong công việc, khách hàng, dự án, học/nghiên cứu, kiến thức, dữ liệu và nội dung truyền thông."/><form className="search-page-form" onSubmit={submit}><Search size={20}/><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ví dụ: đề cương, An Phát, workshop..." autoFocus aria-label="Từ khóa tìm kiếm"/><button className="button primary">Tìm</button></form>
    <div className="result-count">{query?`${results.length} kết quả cho “${query}”`:'Nhập từ khóa để bắt đầu'}</div><Card className="list-card">{results.length?results.map((r,i)=><Link className="search-result" to={r.to} key={`${r.type}-${i}`}><span className="result-icon"><FileText size={18}/></span><div><small>{r.type} · {dateLabel(r.date)}</small><strong>{r.title}</strong><p>{r.description}</p></div><ArrowRight size={17}/></Link>):<Empty title={query?'Không tìm thấy thông tin phù hợp':'Chưa có từ khóa'} description={query?'Thử một tên khách hoặc từ trong ghi chú.':'Tìm kiếm hỗ trợ tiếng Việt có dấu và không dấu.'}/>}</Card>
  </>
}

export function SettingsPage(){
  const {state,reset,clearAll,exportDemo,setSettings}=useDemo();const toast=useToast();const [time,setTime]=useState(state.settings.reminderTime);const [weekdays,setWeekdays]=useState(state.settings.reminderWeekdays)
  const overdue=state.tasks.filter(t=>isOpenTask(t)&&t.dueAt&&t.dueAt<todayISO()).length;const today=state.tasks.filter(t=>isOpenTask(t)&&t.dueAt===todayISO()).length
  const saveSettings=(event:FormEvent)=>{event.preventDefault();setSettings({reminderTime:time,reminderWeekdays:weekdays});toast('Đã lưu cài đặt xem trước trên trình duyệt này; chưa có email được gửi.')}
  const doReset=()=>{if(window.confirm('Khôi phục dữ liệu minh họa? Mọi thay đổi demo trên trình duyệt này sẽ mất.')){reset();toast('Đã khôi phục bộ dữ liệu minh họa.')}}
  const doClearAll=()=>{if(window.confirm('Xóa TOÀN BỘ dữ liệu trên trình duyệt này (khách, cơ hội, dự án, việc, ghi chú, học/kiến thức, nội dung...) để bắt đầu trống? Không thể hoàn tác — chỉ dùng nút "Khôi phục dữ liệu mẫu" để lấy lại bộ minh họa cũ, không lấy lại được dữ liệu anh vừa xóa.')){clearAll();toast('Đã xóa toàn bộ, sẵn sàng bắt đầu trống.')}}
  return <><PageHeading eyebrow="CÀI ĐẶT BẢN THỬ" title="Thiết lập" description="Xem trước cách nhắc việc và quản lý bộ dữ liệu minh họa."/><div className="settings-grid"><div className="stack"><Card title="Nhắc việc hằng ngày"><Notice>Chỉ xem trước. Frontend chưa gửi email hoặc chạy nhắc việc tự động.</Notice><form className="form-grid settings-form" onSubmit={saveSettings}><Field label="Giờ nhận email dự kiến"><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></Field><label className="checkbox-line"><input type="checkbox" checked={weekdays} onChange={e=>setWeekdays(e.target.checked)}/> Chỉ các ngày làm việc</label><button className="button primary" type="submit">Lưu giờ xem trước</button></form><div className="email-preview"><div><Mail size={18}/><strong>Xem trước email hôm nay</strong><span>CHƯA GỬI</span></div><p>Chào anh Hùng, hôm nay có <b>{today}</b> việc đến hạn và <b>{overdue}</b> việc quá hạn. Mở VISUN OS để xem bối cảnh từng việc.</p></div></Card>
      <Card title="Tích hợp"><div className="integration-row"><span className="integration-icon"><CalendarDays size={20}/></span><div><strong>Google Calendar</strong><small>Chưa kết nối · Lịch đang dùng sự kiện minh họa</small></div><span className="badge">Demo</span></div><div className="integration-row"><span className="integration-icon"><Bot size={20}/></span><div><strong>AI Assistant</strong><small>Chưa gọi model · Các tình huống đang mô phỏng</small></div><span className="badge">Demo</span></div></Card></div>
      <div className="stack"><Card title="Thành viên minh họa"><Notice>Danh sách này chỉ để xem giao diện nhóm; chưa có tài khoản hoặc phân quyền thật.</Notice>{state.users.map(u=><div className="member-row" key={u.id}><span className="entity-avatar">{u.initials}</span><div><strong>{u.name}</strong><small>{u.role==='owner'?'Chủ sở hữu':u.role==='member'?'Cộng sự':'Người xem'}</small></div><span className="badge">{u.role==='owner'?'Quản trị':u.role==='member'?'Cập nhật':'Chỉ xem'}</span></div>)}</Card>
      <Card title="Dữ liệu bản thử"><p className="muted">Dữ liệu lưu trên trình duyệt này. Không nhập thông tin khách thật vào bản demo. Tệp JSON xuất ra gồm cả học/nghiên cứu, kiến thức, dữ liệu dự án và nội dung truyền thông.</p><div className="settings-actions"><button className="button outline" onClick={()=>{exportDemo();toast('Đã tải tệp JSON dữ liệu minh họa.')}}><Download size={17}/> Xuất JSON demo</button><button className="button subtle" onClick={doReset}><RotateCcw size={17}/> Khôi phục dữ liệu mẫu</button><button className="button subtle danger" onClick={doClearAll}><Trash2 size={17}/> Xóa toàn bộ, bắt đầu trống</button></div><div className="data-counts"><span>{state.customers.filter(c=>!c.archived).length} khách</span><span>{state.opportunities.filter(o=>!o.archived).length} cơ hội</span><span>{state.projects.filter(p=>!p.archived).length} dự án</span><span>{state.tasks.filter(t=>!t.archived).length} việc</span><span>{state.learning.filter(item=>!item.archived).length} mục học/nghiên cứu</span><span>{state.knowledge.filter(item=>!item.archived).length} kiến thức</span><span>{state.dataAssets.filter(item=>!item.archived).length} tài sản dữ liệu</span><span>{state.content.filter(item=>!item.archived).length} nội dung truyền thông</span></div></Card><Card title="Về bản thử"><div className="about-demo"><ShieldCheck size={24}/><p>VISUN OS frontend demo · AI Trainer workspace. Mọi thao tác chỉ ảnh hưởng bộ dữ liệu minh họa trên thiết bị đang dùng. Các bước xác thực, sao lưu, email, Calendar và AI thật thuộc giai đoạn backend.</p></div></Card></div></div>
  </>
}
