import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

const readState = async (page: import('@playwright/test').Page) => page.evaluate(() => JSON.parse(localStorage.getItem('visun-os-demo-v1') || 'null'))

test('mọi trang chính mở được, có nhãn demo và không tràn ngang', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  for (const path of ['/', '/inbox', '/tasks', '/tasks/t1', '/customers', '/customers/c1', '/opportunities', '/opportunities/o1', '/projects', '/projects/p1', '/learning', '/learning/l1', '/knowledge', '/knowledge/k1', '/data', '/data/da1', '/content', '/content/ct1', '/calendar', '/ai', '/search', '/settings']) {
    await page.goto(path)
    await expect(page.locator('main h1').first()).toBeVisible()
    await expect(page.locator('.demo-pill')).toContainText('BẢN THỬ')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), `tràn ngang tại ${path}`).toBe(true)
  }
  expect(errors).toEqual([])
  const logoWidth = await page.locator(test.info().project.name === 'mobile' ? '.mobile-brand img' : '.brand-block img').evaluate(element => element.getBoundingClientRect().width)
  expect(logoWidth).toBe(test.info().project.name === 'mobile' ? 116 : 140)
})

test('nâng dữ liệu demo cũ giữ nguyên bản ghi đã sửa', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: 'Ghi nhanh' }).fill('Giữ mục thử khi nâng phiên bản')
  await page.getByRole('button', { name: 'Lưu nhanh' }).click()
  await page.evaluate(() => {
    const state = JSON.parse(localStorage.getItem('visun-os-demo-v1') || '{}')
    state.version = 1
    delete state.learning; delete state.knowledge; delete state.dataAssets
    localStorage.setItem('visun-os-demo-v1', JSON.stringify(state))
  })
  await page.reload()
  const state = await readState(page)
  expect(state.version).toBe(3)
  expect(state.inbox.some((item: { content: string }) => item.content === 'Giữ mục thử khi nâng phiên bản')).toBe(true)
  expect(state.learning).toHaveLength(6)
  expect(state.knowledge).toHaveLength(8)
  expect(state.dataAssets).toHaveLength(6)
  expect(state.content).toHaveLength(3)
})

test('nâng dữ liệu phiên bản 2 giữ các mục đã nhập', async ({ page }) => {
  await page.goto('/inbox')
  await page.getByLabel('Nội dung ghi nhanh').fill('Ý tưởng đã nhập trước khi có module nội dung')
  await page.getByRole('button', { name: 'Lưu ghi nhanh' }).click()
  await page.evaluate(() => {
    const state = JSON.parse(localStorage.getItem('visun-os-demo-v1') || '{}')
    state.version = 2
    delete state.content
    localStorage.setItem('visun-os-demo-v1', JSON.stringify(state))
  })
  await page.reload()
  const state = await readState(page)
  expect(state.version).toBe(3)
  expect(state.inbox.some((item: { content: string }) => item.content === 'Ý tưởng đã nhập trước khi có module nội dung')).toBe(true)
  expect(state.content).toHaveLength(3)
})

test('tạo nghiên cứu, cập nhật tiến độ và lưu bài học liên kết', async ({ page }) => {
  await page.goto('/learning')
  await page.getByRole('button', { name: 'Thêm nội dung' }).click()
  const form = page.getByRole('dialog', { name: 'Thêm nội dung học/nghiên cứu' })
  await form.getByLabel('Tên nội dung').fill('Nghiên cứu đo hiệu quả AI')
  await form.locator('select').nth(0).selectOption('research')
  await form.locator('select').nth(1).selectOption('active')
  await form.getByLabel('Mục tiêu / câu hỏi cần trả lời').fill('Tìm chỉ số có thể kiểm tra từ đầu ra công việc.')
  await form.getByLabel('Tiến độ (%)').fill('30')
  await form.getByLabel('Bước tiếp theo').fill('Viết bộ tiêu chí')
  await form.locator('select').nth(2).selectOption('p3')
  await form.getByRole('button', { name: 'Tạo mới' }).click()
  await expect(page.locator('main h1')).toHaveText('Nghiên cứu đo hiệu quả AI')
  await page.getByRole('button', { name: 'Chỉnh sửa' }).click()
  const edit = page.getByRole('dialog', { name: 'Chỉnh sửa học/nghiên cứu' })
  await edit.getByLabel('Tiến độ (%)').fill('75')
  await edit.getByLabel('Ghi chú / điều đã học').fill('Cần đo đầu ra, không chỉ số lượt dùng.')
  await edit.getByRole('button', { name: 'Lưu thay đổi' }).click()
  await page.getByRole('button', { name: 'Lưu thành kiến thức' }).click()
  const knowledge = page.getByRole('dialog', { name: 'Lưu bài học vào kho kiến thức' })
  await knowledge.getByLabel('Từ khóa').fill('đo lường, workshop')
  await knowledge.getByRole('button', { name: 'Tạo mới' }).click()
  await expect(page.locator('main h1')).toContainText('Bài học từ: Nghiên cứu đo hiệu quả AI')
  const state = await readState(page)
  const learning = state.learning.find((item: { title: string }) => item.title === 'Nghiên cứu đo hiệu quả AI')
  const entry = state.knowledge.find((item: { learningId: string }) => item.learningId === learning.id)
  expect(learning.progress).toBe(75)
  expect(entry.projectId).toBe('p3')
  expect(entry.tags).toEqual(['đo lường', 'workshop'])
  await page.reload()
  await expect(page.getByRole('link', { name: /Nghiên cứu đo hiệu quả AI/ })).toBeVisible()
})

test('dữ liệu dự án lọc, lưu văn bản và xuất đủ JSON', async ({ page }) => {
  await page.goto('/data?project=p3')
  await page.getByRole('button', { name: 'Thêm dữ liệu' }).click()
  const dialog = page.getByRole('dialog', { name: 'Thêm tài sản dữ liệu' })
  await dialog.getByLabel('Tên dữ liệu / tài liệu').fill('Bảng kiểm tra dữ liệu thử')
  await dialog.locator('select').nth(0).selectOption('table')
  await dialog.getByLabel('Mô tả / mục đích').fill('Danh sách trường dữ liệu của dự án.')
  await dialog.getByLabel('Nội dung / cấu trúc dữ liệu').fill('Tên trường | Người nhập | Nguồn')
  await dialog.getByLabel('Định dạng').fill('CSV mẫu')
  await dialog.getByRole('button', { name: 'Tạo mới' }).click()
  await expect(page.locator('main h1')).toHaveText('Bảng kiểm tra dữ liệu thử')
  await page.goto('/data?project=p3')
  await expect(page.getByRole('link', { name: /Bảng kiểm tra dữ liệu thử/ })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Xuất toàn bộ JSON' }).click()
  const download = await downloadPromise
  const exported = JSON.parse(await readFile(await download.path(), 'utf8'))
  expect(exported.dataAssets.find((item: { title: string }) => item.title === 'Bảng kiểm tra dữ liệu thử').projectId).toBe('p3')
  expect(exported.learning).toHaveLength(6)
  expect(exported.knowledge).toHaveLength(8)
  await page.goto('/search?q=bang%20kiem%20tra%20du%20lieu%20thu')
  await expect(page.getByRole('link', { name: /Bảng kiểm tra dữ liệu thử/ })).toBeVisible()
})

test('tài liệu mẫu sửa được và trang dữ liệu mở đủ bối cảnh dự án', async ({ page }) => {
  await page.goto('/data/da1')
  await page.getByRole('button', { name: 'Chỉnh sửa' }).click()
  const dialog = page.getByRole('dialog', { name: 'Chỉnh sửa tài sản dữ liệu' })
  await dialog.getByLabel('Mô tả / mục đích').fill('Đề cương mẫu đã cập nhật mô tả.')
  await dialog.getByRole('button', { name: 'Lưu thay đổi' }).click()
  await expect(page.getByText('Đề cương mẫu đã cập nhật mô tả.')).toBeVisible()
  await expect(page.getByRole('link', { name: /Mở liên kết nguồn/ })).toHaveAttribute('href', '/demo/de-cuong-workshop.txt')
  await page.goto('/data?project=p3')
  await expect(page.getByText('Trao đổi nhu cầu An Phát')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Gửi đề cương AI cho Công ty An Phát' }).first()).toBeVisible()
  if (test.info().project.name === 'mobile') {
    await page.getByRole('button', { name: 'Mở thêm trang' }).click()
    await page.locator('.mobile-menu').getByRole('link', { name: 'Kho kiến thức' }).click()
    await expect(page.getByRole('heading', { name: 'Kho kiến thức', exact: true })).toBeVisible()
  }
})

test('ghi nhanh, tải lại và chuyển thành việc có nguồn', async ({ page }) => {
  await page.goto('/inbox')
  const content = 'Gửi đề cương cho Công ty An Phát thứ Sáu - thử nghiệm'
  await page.getByLabel('Nội dung ghi nhanh').fill(content)
  await page.getByRole('button', { name: 'Lưu ghi nhanh' }).click()
  await page.reload()
  const row = page.locator('.inbox-row').filter({ hasText: content })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: '+ Việc' }).click()
  const dialog = page.getByRole('dialog', { name: 'Tạo việc từ ghi nhanh' })
  await dialog.locator('select').nth(2).selectOption('c1')
  await dialog.getByRole('button', { name: 'Tạo mới' }).click()
  await expect(row).toHaveCount(0)
  await page.getByRole('button', { name: 'Tất cả' }).click()
  const processed = page.locator('.inbox-row').filter({ hasText: content })
  await expect(processed).toContainText('Đã phân loại')
  await processed.getByRole('link', { name: 'Mở mục đã tạo' }).click()
  await expect(page.locator('main h1')).toHaveText(content)
  await expect(page.getByText('Nguồn tạo việc')).toBeVisible()
  const state = await readState(page)
  expect(state.tasks.find((task: { title: string }) => task.title === content).sourceInboxId).toBeTruthy()
})

test('ý tưởng từ hộp ghi nhanh đi qua lịch đăng và gắn công việc', async ({ page }) => {
  await page.goto('/inbox')
  const idea = 'CEO theo dõi cam kết sau cuộc họp như thế nào?'
  await page.getByLabel('Nội dung ghi nhanh').fill(idea)
  await page.getByRole('button', { name: 'Lưu ghi nhanh' }).click()
  await page.locator('.inbox-row').filter({ hasText: idea }).getByRole('button', { name: '+ Nội dung' }).click()
  const form = page.getByRole('dialog', { name: 'Thêm ý tưởng truyền thông' })
  await expect(form.getByLabel('Tên ý tưởng / nội dung')).toHaveValue(idea)
  await form.getByLabel('Góc triển khai').fill('Một tình huống thực tế cần được xác nhận.')
  await form.getByLabel('LinkedIn').check()
  await form.getByRole('button', { name: 'Thêm nội dung' }).click()
  await expect(page.locator('main h1')).toHaveText(idea)
  await page.getByRole('button', { name: 'Tạo công việc' }).click()
  await expect(page.getByRole('link', { name: 'Mở việc liên quan' })).toBeVisible()
  const facebook = page.locator('.content-publication').filter({ hasText: 'Facebook' })
  await facebook.getByLabel('Ngày dự kiến').fill(await page.evaluate(() => new Date().toLocaleDateString('en-CA')))
  await facebook.getByLabel('Link bài đã đăng').fill('https://example.com/bai-viet')
  await facebook.getByLabel('Cuộc trò chuyện').fill('2')
  await facebook.getByRole('button', { name: 'Lưu kênh này' }).click()
  const state = await readState(page)
  const content = state.content.find((item: { title: string }) => item.title === idea)
  expect(content.sourceType).toBe('inbox')
  expect(content.status).toBe('published')
  expect(content.publications).toHaveLength(2)
  expect(content.publications.find((pub: { channel: string }) => pub.channel === 'facebook').conversations).toBe(2)
  expect(state.tasks.some((task: { id: string }) => task.id === content.taskId)).toBe(true)
  await page.reload()
  await expect(page.getByRole('link', { name: 'Mở bài đăng' })).toHaveAttribute('href', 'https://example.com/bai-viet')
  await page.goto('/content')
  await page.getByRole('button', { name: 'Lịch đăng' }).click()
  await expect(page.getByText(idea).first()).toBeVisible()
})

test('hoàn thành rồi mở lại việc quá hạn cập nhật dashboard', async ({ page }) => {
  await page.goto('/')
  const card = page.locator('.summary-card').filter({ hasText: 'Đã quá hạn' })
  const before = Number(await card.locator('.summary-num').textContent())
  await page.goto('/tasks/t1')
  await page.getByRole('button', { name: 'Hoàn thành', exact: true }).click()
  await page.goto('/')
  await expect(card.locator('.summary-num')).toHaveText(String(before - 1))
  await page.goto('/tasks/t1')
  await page.getByRole('button', { name: 'Mở lại', exact: true }).click()
  await page.goto('/')
  await expect(card.locator('.summary-num')).toHaveText(String(before))
})

test('việc chờ phản hồi cần ngày hỏi lại và lưu đúng trạng thái', async ({ page }) => {
  await page.goto('/tasks/t1')
  await page.getByRole('button', { name: 'Chỉnh sửa' }).click()
  const dialog = page.getByRole('dialog', { name: 'Chỉnh sửa công việc' })
  await dialog.getByLabel('Trạng thái').selectOption('waiting')
  await dialog.getByRole('button', { name: 'Lưu thay đổi' }).click()
  await expect(dialog.getByText('Việc chờ phản hồi cần ngày hỏi lại.')).toBeVisible()
  await dialog.getByLabel('Ngày hỏi lại / xem lại').fill('2026-10-01')
  await dialog.getByRole('button', { name: 'Lưu thay đổi' }).click()
  await expect(page.getByText('Chờ phản hồi', { exact: true }).first()).toBeVisible()
  const state = await readState(page)
  expect(state.tasks.find((task: { id: string }) => task.id === 't1').reviewAt).toBe('2026-10-01')
})

test('hồ sơ B2B giữ liên hệ, cơ hội và cam kết đúng khách', async ({ page }) => {
  await page.goto('/customers/c1')
  await expect(page.locator('main h1')).toHaveText('Công ty An Phát')
  await expect(page.getByText('Nguyễn Minh Anh').first()).toBeVisible()
  await expect(page.getByText('Lê Quốc Bảo')).toBeVisible()
  await expect(page.getByText('Chương trình AI cho quản lý')).toBeVisible()
  await expect(page.getByText('Tư vấn workflow báo cáo')).toBeVisible()
  await expect(page.getByText('Gửi đề cương AI cho Công ty An Phát').first()).toBeVisible()
})

test('thêm người liên hệ và ghi chú vào đúng hồ sơ khách', async ({ page }) => {
  await page.goto('/customers/c1')
  await page.locator('.subheading-row').getByRole('button', { name: '+ Thêm' }).click()
  await page.getByPlaceholder('Tên người liên hệ').fill('Người liên hệ thử')
  await page.getByPlaceholder('Vai trò').fill('Phụ trách triển khai')
  await page.getByRole('button', { name: 'Lưu người liên hệ' }).click()
  await page.getByRole('button', { name: 'Ghi chú', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Ghi chú cuộc trao đổi' })
  await dialog.getByLabel('Tiêu đề').fill('Ghi chú kiểm tra liên kết')
  await dialog.getByLabel('Nội dung').fill('Khách muốn xem ví dụ thực hành.')
  await dialog.getByRole('button', { name: 'Tạo mới' }).click()
  await page.reload()
  await expect(page.getByText('Người liên hệ thử')).toBeVisible()
  await expect(page.getByText('Ghi chú kiểm tra liên kết')).toBeVisible()
  const state = await readState(page)
  expect(state.customers.find((item: { id: string }) => item.id === 'c1').contacts).toHaveLength(3)
  expect(state.notes.find((item: { title: string }) => item.title === 'Ghi chú kiểm tra liên kết').customerId).toBe('c1')
})

test('chốt cơ hội rồi tạo dự án có liên kết ngược', async ({ page }) => {
  await page.goto('/opportunities/o2')
  await page.getByRole('button', { name: 'Đã chốt' }).click()
  await page.getByRole('button', { name: 'Tạo dự án' }).click()
  await expect(page.locator('main h1')).toContainText('Tư vấn workflow báo cáo')
  const state = await readState(page)
  const project = state.projects.find((item: { opportunityId: string }) => item.opportunityId === 'o2')
  expect(project).toBeTruthy()
  expect(project.customerId).toBe('c1')
  await page.reload()
  await expect(page.getByRole('link', { name: /Tư vấn workflow báo cáo/ }).first()).toBeVisible()
})

test('lịch cho phép gắn khách và mở hồ sơ, luôn ghi rõ minh họa', async ({ page }) => {
  await page.goto('/calendar')
  await expect(page.getByText('chưa kết nối Google', { exact: false })).toBeVisible()
  await page.locator('.calendar-event:not(.cancelled)').first().click()
  const dialog = page.getByRole('dialog', { name: 'Cuộc hẹn minh họa' })
  await dialog.getByLabel('Gắn khách hàng').selectOption('c1')
  await dialog.getByRole('button', { name: 'Lưu liên kết demo' }).click()
  await page.locator('.calendar-event:not(.cancelled)').first().click()
  await dialog.getByRole('link', { name: 'Mở hồ sơ khách' }).click()
  await expect(page.locator('main h1')).toHaveText('Công ty An Phát')
})

test('dự án thêm mốc và việc lặp chỉ sinh kỳ sau một lần', async ({ page }) => {
  await page.goto('/projects/p1')
  await page.getByLabel('Tên mốc mới').fill('Mốc kiểm tra')
  await page.getByLabel('Ngày mốc mới').fill('2026-10-05')
  await page.getByRole('button', { name: '+ Thêm mốc' }).click()
  await expect(page.getByText('Mốc kiểm tra')).toBeVisible()
  await page.goto('/tasks/t30')
  const before = (await readState(page)).tasks.length
  await page.getByRole('button', { name: 'Hoàn thành', exact: true }).click()
  expect((await readState(page)).tasks.length).toBe(before + 1)
  await page.getByRole('button', { name: 'Mở lại', exact: true }).click()
  await page.getByRole('button', { name: 'Hoàn thành', exact: true }).click()
  expect((await readState(page)).tasks.length).toBe(before + 1)
})

test('AI mô phỏng cho sửa, loại, chốt một lần và từ chối chốt trùng', async ({ page }) => {
  await page.goto('/ai')
  await page.getByRole('button', { name: /Từ cuộc gọi tạo việc/ }).click()
  const proposal = page.locator('.proposal-panel')
  await expect(proposal).toBeVisible()
  const before = (await readState(page))?.tasks?.length ?? 36
  await proposal.locator('.proposal-item').first().getByRole('checkbox').uncheck()
  await proposal.locator('.proposal-item').nth(1).getByLabel('Tên mục').fill('Việc AI demo đã sửa')
  await proposal.getByRole('button', { name: 'Chốt và lưu' }).click()
  await expect(proposal.getByText('Đã lưu 1 mục', { exact: false })).toBeVisible()
  await proposal.getByRole('button', { name: 'Chốt và lưu' }).click()
  await expect(proposal.getByText('Bản nháp này đã được chốt trước đó', { exact: false })).toBeVisible()
  const state = await readState(page)
  expect(state.tasks.length).toBe(before + 1)
  expect(state.tasks.filter((task: { title: string }) => task.title === 'Việc AI demo đã sửa')).toHaveLength(1)
})

test('tìm tiếng Việt không dấu và reset khôi phục dữ liệu mẫu', async ({ page }) => {
  await page.goto('/search?q=khao%20sat')
  await expect(page.getByRole('link', { name: /Khảo sát đội kinh doanh Sao Việt/ })).toBeVisible()
  await page.goto('/inbox')
  await page.getByLabel('Nội dung ghi nhanh').fill('Mục thử reset')
  await page.getByRole('button', { name: 'Lưu ghi nhanh' }).click()
  await page.goto('/settings')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Khôi phục dữ liệu mẫu' }).click()
  await page.goto('/inbox')
  await expect(page.getByText('Mục thử reset')).toHaveCount(0)
  const state = await readState(page)
  expect(state.customers).toHaveLength(10)
  expect(state.tasks).toHaveLength(36)
})
